zuul:
  routes:
    demo-dept: /ccc/**
#  ignored-patterns:
#    - /**/demo-dept/zuulTest
  sensitive-headers:
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时


spring:
  rabbitmq:
    host: 192.168.1.182
    port: 5672
    username: guest
    password: guest  

management:
  endpoints:
    web:
      exposure:
        include: "*"
