zuul:
  routes:
    demo-dept: /bbb/**
#  ignored-patterns:
#    - /**/demo-dept/zuulTest
  sensitive-headers:


spring:
  rabbitmq:
    host: 192.168.1.182
    port: 5672
    username: guest
    password: guest  

management:
  endpoints:
    web:
      exposure:
        include: "*"
