zuul:
  routes:
    microservice-dept: /ccc/**
  sensitive-headers:

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000 


spring:
  rabbitmq:
    host: 192.168.1.182
    port: 5672
    username: guest
    password: guest  

management:
  endpoints:
    web:
      exposure:
        include: "*"
